### ISSUE TITLE
Thread safe request context

### ISSUE THREAD

**Issue by lsnpatryks** [imindeu/play-cxf#3]
Is it possible with this module to achieve thread safe request context? I found some documentation on official cxf website (http://cxf.apache.org/faq.html) and that part of code:

    ((BindingProvider)proxy).getRequestContext().put("thread.local.request.context", "true");

**Comment by kustra** [comment]
The documentation indicated is about client proxies. Not server side. play-cxf is server side only. You don't need to use it for calling other SOAP services. I think all available SOAP clients should work well together with Play out-of-the-box.
