### ISSUE TITLE
I can't add sample requests in SoapUI

### ISSUE THREAD

**Issue by martin5211** [imindeu/play-cxf#7]
I got these logs messages in SoapUI:

Wed Sep 16 11:55:23 ART 2015:INFO:Finding importer for {http://localhost:9000/service/person}PersonServiceImplServiceSoapBinding
Wed Sep 16 11:55:23 ART 2015:INFO:Missing importer for {http://localhost:9000/service/person}PersonServiceImplServiceSoapBinding

The wsdl response is:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns1="http://services/" xmlns:ns2="http://cxf.apache.org/transports/play" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://localhost:9000/service/person" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="PersonServiceImplService" targetNamespace="http://localhost:9000/service/person">
   <wsdl:import location="/service/person?wsdl=PersonService.wsdl" namespace="http://services/" />
   <wsdl:binding name="PersonServiceImplServiceSoapBinding" type="ns1:PersonService">
      <soap:binding style="document" transport="http://cxf.apache.org/transports/play" />
      <wsdl:operation name="getNames">
         <soap:operation soapAction="" style="document" />
         <wsdl:input name="getNames">
            <soap:body use="literal" />
         </wsdl:input>
         <wsdl:output name="getNamesResponse">
            <soap:body use="literal" />
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>
   <wsdl:service name="PersonServiceImplService">
```

I can't test the web service made with play-cxf.

**Comment by kustra** [comment]
Have a look at the current play-cxf-hello sample's applicationContext.xml.
There is a transportId property somewhere in there. Compare it with your
app's config.
I'll add a FAQ entry about this later.
Cheers,
L
2015.09.16. 17:07 ezt írta ("Martin Caminoa" <notifications@github.com>):

**Comment by martin5211** [comment]
It works excellent!

Thank you @kustra

**Comment by kustra** [comment]
I also updated the blog post on http://www.imind.eu/web/2013/11/07/developing-soap-services-using-play-framework-2-2-x/ so now it shows the correct code samples.
